### ISSUE TITLE
pre-built images are NOT published to GHCR

### ISSUE THREAD

**Issue by mariushosting** [Worklenz/worklenz#72]
pre-built Docker images are NOT published to GHCR. @chamikaJ

**Comment by kithmina1999** [comment]
@mariushosting  
The fix for this issue is already in a pending pull request: [#71](https://github.com/Worklenz/worklenz/pull/71).
The relevant commit addressing this can be found here: [2c8d237](https://github.com/Worklenz/worklenz/pull/71/commits/2c8d237a2db12513bdc2df1db28024e9c08e9d68).
Once the PR is approved and merged, this issue should be resolved.

**Comment by kalinga777** [comment]
@mariushosting  - Please check the latest version

**Comment by JMpixel** [comment]
This wasn't fixed as far as I can tell. I can see your actions are building the images on release, but they're not actually published and accessible to the public.

**Comment by kithmina1999** [comment]
@JMpixel We removed the prebuilt images from docker-compose because they caused issues in remote server setups, so now we rely on local build instructions instead. If we add separate docker-compose for local setup we will publish prebuild images
